# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_auto_20171111_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course_id',
            new_name='course',
        ),
    ]
