# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0005_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='dojo_ninjas.Book'),
        ),
    ]
